### ISSUE TITLE
Images not centering witout padding

### ISSUE THREAD

**Issue by grinchdubs** [SonarSonic/DrawingBotV3#117] opened 2023-12-20 23:56 UTC
**Describe the bug**
When using an 11 by 8.5 paper size I was unable to center the image on the sheet of paper without padding.

**To Reproduce**
1. set paper size to 11in by 8.5in
2. import the image below
![ColorHighwayShort3](https://github.com/SonarSonic/DrawingBotV3/assets/26509343/324a115c-0473-4527-8016-61bf2cbcdd2a)

**Expected behavior**
I would expect the image to be center in the long dimension.

**Screenshots**
![PXL_20231220_184009520](https://github.com/SonarSonic/DrawingBotV3/assets/26509343/5da37f59-a76f-4dea-9ddc-69fbec0a6c09)
![PXL_20231220_205148165 MP](https://github.com/SonarSonic/DrawingBotV3/assets/26509343/c98a4ef5-ec82-4ff0-bf07-808e1a69fcc3)

**DrawingBotV3 Version**
v1.6.9-Premium.jar

**Operating System**
Windows 11

**Comment by SonarSonic** [comment] 2023-12-21 11:56
Will be fixed in next version, the issue is present only in inches/cm. Switch to mm before final processing to fix until the new version is out.

**Closed by SonarSonic** 2023-12-21 11:56 UTC
Labels: bug
